name: Gollum Slack Notification

on: gollum

jobs:
  job:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dump github.event
        # github.eventの中身を見たい
        env:
          EVENT: ${{ toJson(github.event) }}
        run: echo "${EVENT}"
      - name: Read info edited/created pages
        # JavaScriptにgithub.eventの値を渡す
        uses: ./
        with:
          event: ${{ toJson(github.event) }}
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Successfully automated deployment.
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "event",
                    "value": "${{ github.event.pages[0] }}"
                  },
                  {
                    "title": "Title",
                    "value": "${{ github.event.pages.title }}"
                  },
                  {
                    "title": "Wiki URL",
                    "value": "${{ github.event.pages.html_url }}"
                  },
                  {
                    "title": "Action",
                    "value": "${{ github.event.pages.action }}"
                  }
                ]
              }
            ]
